// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0DyiuAvb90qM5GWMA7HOt1aPoFIDHsXs',
    appId: '1:385512801302:web:d4ccd836ea36123a41a137',
    messagingSenderId: '385512801302',
    projectId: 'sleekscan-6defd',
    authDomain: 'sleekscan-6defd.firebaseapp.com',
    storageBucket: 'sleekscan-6defd.firebasestorage.app',
    measurementId: 'G-7GL83TZGDE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7WqBYgfFJxBZ1YsHLHDu8roWZI6TO7PE',
    appId: '1:385512801302:android:521e37a6b179d3f341a137',
    messagingSenderId: '385512801302',
    projectId: 'sleekscan-6defd',
    storageBucket: 'sleekscan-6defd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcmqz-gSySiEnZGWSJMqmukPQoGqvng6w',
    appId: '1:385512801302:ios:9912c90e8e24e93c41a137',
    messagingSenderId: '385512801302',
    projectId: 'sleekscan-6defd',
    storageBucket: 'sleekscan-6defd.firebasestorage.app',
    iosBundleId: 'com.example.docscanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcmqz-gSySiEnZGWSJMqmukPQoGqvng6w',
    appId: '1:385512801302:ios:9912c90e8e24e93c41a137',
    messagingSenderId: '385512801302',
    projectId: 'sleekscan-6defd',
    storageBucket: 'sleekscan-6defd.firebasestorage.app',
    iosBundleId: 'com.example.docscanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0DyiuAvb90qM5GWMA7HOt1aPoFIDHsXs',
    appId: '1:385512801302:web:e3afa055ba4dcf8f41a137',
    messagingSenderId: '385512801302',
    projectId: 'sleekscan-6defd',
    authDomain: 'sleekscan-6defd.firebaseapp.com',
    storageBucket: 'sleekscan-6defd.firebasestorage.app',
    measurementId: 'G-6TCFXYKH13',
  );
}
